version: '3.7'
services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: ${RABBITMQ_CONTAINER_NAME}
    hostname: "${RABBITMQ_HOSTNAME}"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_USER}
    ports:
      - "${RABBITMQ_PORT_CON_DOCKER}:${RABBITMQ_PORT_CON_EXT}" # Message Queue Main Port
      - "${RABBITMQ_PORT_WEB_DOCKER}:${RABBITMQ_PORT_WEB_EXT}"
    volumes:
      - /var/lib/rabbitmq

  allnetcrawler:
    build:
      context: .
    container_name: ${ALLNETCRAWLER_NAME}
    depends_on:
      - rabbitmq
    restart: always
    environment:
      - RABBIT_HOST=${RABBITMQ_HOSTNAME}

volumes:
  rabbit1-volume:
    driver: local

networks:
  default:
    name: ${NETWORK_NAME}
