version: '3.7'
services:
  dmis_db:
    image: "postgres:11"
    container_name: "dmis_db-container"
    restart: always
    environment:
      - POSTGRES_USER=dmis_dbuser
      - POSTGRES_PASSWORD=dmis_dbpassword
      - POSTGRES_DB=dmis_recordings_db
    volumes:
      - /docker/projects/lehner/postgresql/data
    ports:
      - "6543:5432"

  pika_consumer1:
    build: .
    container_name: "pika_consumer1"
    depends_on:
      - dmis_db
    restart: always
    command: ["./wait-for-it.sh", "dmis_db:6543", "--", "python3", "-u", "./pika_consumer.py"]
    environment:
      - BLADL_SETUP_NR=BLADL_00
      - RABBIT_HOST=rabbit1

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=132.231.59.224:6543
      - ADMINER_DEFAULT_USER=dmis_dbuser
      - ADMINER_DEFAULT_PASSWORD=dmis_dbpassword
    ports:
    - "8282:8282"
    command:
      - 'php'
      - '-S'
      - '[::]:8282'
      - '-t'
      - '/var/www/html'
    entrypoint:
      - 'entrypoint.sh'
      - 'docker-php-entrypoint'

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - "3050:3000"

volumes:
  dmis_db-volume:
    driver: local


networks:
  default:
    external: true
    name: mttq-net
